version: "3"
dotenv: ['{{ .ENV }}.env']
vars:
  SSH_ADDRESS:
    sh: cd infra && terraform output -raw ssh_address
tasks:
  dev:
    deps:
      - dev:server
      - dev:client # Run both servers in watch mode...
  dev:client:
    dir: client
    cmds:
      - pnpm install
      - pnpm run dev
  dev:server:
    cmds:
      - "air serve --http=$VITE_POCKETBASE_URL"
  build:
    deps:
      - build:client
      - build:server
  build:client:
    dir: client
    cmds:
      - pnpm install
      - pnpm run build
  build:server:
    cmds:
      - GOOS=$GOOS GOARCH=$GOARCH CGO_ENABLED=0 go build -o pocketbase
  serve:
    deps:
      - build
    cmds:
      - ENV=production ./pocketbase serve
  connect:
    dir: infra
    cmds:
      - exec $(terraform output -raw ssh)
  deploy:
    deps:
      - build
    cmds:
      - rsync -av -e "ssh -i ~/.ssh/{{ .KEY_NAME }}.pem" pb_public pocketbase pb_migrations Taskfile.yml "ec2-user@{{ .SSH_ADDRESS }}:/home/ec2-user/"
  infra:build:
    dir: infra
    cmds:
      - terraform init -var="key_name=$KEY_NAME"
      - terraform apply -var="key_name=$KEY_NAME"
  infra:destroy:
    dir: infra
    cmds:
      - terraform destroy -var="key_name=$KEY_NAME"
  open:
    dir: infra
    cmds:
      - open $(terraform output -raw instance_ip_addr)
