version: "3"
vars:
  SSH_ADDRESS:
    sh: cd infra && terraform output -raw ssh_address
  CURRENT_OS:
    sh: uname
tasks:
  dev:
    deps:
      - dev:server
      - dev:client # Run both servers in watch mode...
  dev:client:
    dir: client
    dotenv: ['.env.development', '../.env.development']
    cmds:
      - pnpm install
      - pnpm run dev
  dev:server:
    dotenv: ['.env.development', 'client/.env.development']
    cmds:
      - "air serve --http=$VITE_POCKETBASE_URL"
  build:
    deps:
      - build:client
      - build:server
  build:client:
    dir: client
    dotenv: ['.env.production', '../.env.production']
    cmds:
      - pnpm install
      - pnpm run build
  build:server:
    dotenv: ['.env.production', 'client/.env.production']
    cmds:
      - GOOS=$GOOS GOARCH=$GOARCH CGO_ENABLED=0 go build -o pocketbase
  connect:
    dir: infra
    dotenv: ['../.env.production', '../client/.env.production']
    cmds:
      - exec $(terraform output -raw ssh)
  deploy:
    dotenv: ['.env.production', 'client/.env.production']
    deps:
      - build
    cmds:
      - rsync -av -e "ssh -i ~/.ssh/$KEY_NAME.pem" pb_public pocketbase pb_migrations Taskfile.yml "ec2-user@{{ .SSH_ADDRESS }}:/home/ec2-user/"
  infra:apply:
    dir: infra
    dotenv: ['../.env.production', '../client/.env.production']
    cmds:
      - terraform init -var="key_name=$KEY_NAME"
      - terraform apply -var="key_name=$KEY_NAME"
    preconditions:
      - sh: '[ "$KEY_NAME" != "" ]'
        msg: Key name cannot be empty
  infra:destroy:
    dir: infra
    dotenv: ['../.env.production', '../client/.env.production']
    cmds:
      - terraform destroy -var="key_name=$KEY_NAME"
  open:
    dir: infra
    dotenv: ['../.env.production', '../client/.env.production']
    cmds:
      - open "http://$(terraform output -raw instance_ip_addr)"
