version: "3"
vars:
  KEY_NAME: "ec2-key-pair"
  SSH_ADDRESS:
    sh: cd ./infra && terraform output -raw ssh_address
tasks:
  dev:
    deps:
      - dev:server
      - dev:client # Run both servers in watch mode...
  build:
    deps:
      - build:client
      - build:server
  dev:client:
    cmds:
      - cd client && pnpm install
      - cd client && pnpm run dev
  dev:server:
    cmds:
      - air serve --http=127.0.0.1:8080
  build:server:
    cmds:
      - go build -o pocketbase
  build:client:
    cmds:
      - cd client && pnpm install
      - cd client && pnpm run build
  connect:
    cmds:
      - cd ./infra && exec $(terraform output -raw ssh)
  deploy:
    deps:
      - build
    cmds:
      - 'rsync -av -e "ssh -i ~/.ssh/{{ .KEY_NAME }}.pem" pb_public pocketbase pb_migrations "ec2-user@{{ .SSH_ADDRESS }}:/home/ec2-user/"'
  infra:
    cmds:
      - cd infra && terraform init
      - 'cd infra && terraform apply -var="key_name={{.KEY_NAME}}"'
